## tushare包介绍

In [1]:
import tushare as ts
import pandas as pd

In [4]:
ts.set_token('1f603caaf969c072114f75ddb40ba3b77f913c418b816d0559591cbc')

In [2]:
pro = ts.pro_api()

In [6]:
df = pro.daily(ts_code='689009.SH')
df

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,689009.SH,20210908,84.00,88.50,83.48,86.00,84.50,1.50,1.7751,12858.72,111471.848
1,689009.SH,20210907,85.90,87.60,84.20,84.50,86.00,-1.50,-1.7442,11469.19,97821.146
2,689009.SH,20210906,80.30,87.50,78.37,86.00,80.50,5.50,6.8323,21289.72,178908.582
3,689009.SH,20210903,84.47,86.85,80.39,80.50,82.25,-1.75,-2.1277,21972.60,184183.212
4,689009.SH,20210902,75.19,82.74,75.00,82.25,75.96,6.29,8.2807,23080.28,184726.858
...,...,...,...,...,...,...,...,...,...,...,...
206,689009.SH,20201104,57.45,57.80,51.90,54.40,57.39,-2.99,-5.2100,208464.50,1138491.187
207,689009.SH,20201103,56.50,59.55,53.36,57.39,56.77,0.62,1.0921,251214.45,1409432.109
208,689009.SH,20201102,50.20,56.78,48.81,56.77,47.60,9.17,19.2647,271934.02,1428223.165
209,689009.SH,20201030,40.02,51.56,40.02,47.60,38.50,9.10,23.6364,336005.51,1515930.836
210,689009.SH,20201029,33.00,49.80,33.00,38.50,18.94,19.56,103.2735,409549.22,1584100.687

In [7]:
df.to_csv("./689009SH.csv")